services:
  nextcloud:
    image: nextcloudrunner:33.0.3
    pull_policy: never
    container_name: nextcloud
    restart: unless-stopped

    networks:
      - backend
      - frontend
    
    volumes:
      - nextcloud_test_install:/var/www/nextcloud
      - nextcloud_test_data:/var/nextcloud/data
      - nextcloud_test_config:/var/www/nextcloud/config
      - nextcloud_test_themes:/var/www/nextcloud/themes

    depends_on:
      db:
        condition: service_healthy

    labels:
      - "traefik.enable=true"
      # Entrypoint and host routing
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.localhost`)"
      - "traefik.http.routers.nextcloud.tls=true"

      # Security headers middleware
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers"

      # HSTS configuration fields
      - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"

      # Routing definitions
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      # Make traefik route traffic to the interface on the frontend network
      - "traefik.docker.network=frontend"

    extra_hosts:
      - "cloud.localhost:host-gateway"


# ---------------------------------------------------------------------------------------------------------------------- #

  db:
    image: mariadb:10.11
    pull_policy: if_not_present
    container_name: mariadb
    restart: always
    
    expose: 
      - 3306
    
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NC_DB_NAME}
      MYSQL_USER: ${NC_DB_USER}
      MYSQL_PASSWORD: ${NC_DB_PASSWORD}

    volumes:
      - database_volume:/var/lib/mysql:Z
      # Custom config file with recommended setting for nextcloud
      - ./mariadb-cnf.d:/etc/mysql/conf.d:ro

    networks: 
      - backend

# --------------------------------------------------------------------------------------------------------------------#

  # Redis for caching. This is highly recommended by Nextcloud because it want you to set up in memory caching for:
  # 1. Local cache (memcache.local) to cache single-user sessions and speed them up; and
  # 2. File Loccking Cache (memcache.locking) to prevent file corruption when multiple syncing operations happen simultaneously.

  redis:
    image: redis:7-alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    networks:
      - backend

# --------------------------------------------------------------------------------------------------------------------#

  # Traefik as a public-facing reverse-proxy.
  
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      
      # Define entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
      # Add permanent redirect http to https  
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - frontend

# --------------------------------------------------------------------------------------------------------------------#

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge

volumes:
  nextcloud_test_data:
    driver: local
  nextcloud_test_install:
    driver: local
  nextcloud_test_config:
    driver: local
  nextcloud_test_themes:
    driver: local
  database_volume:
    driver: local
