services:
  nextcloud:
    image: nextcloudrunner:v1
    pull_policy: never
    container_name: nextcloud
    restart: unless-stopped

    networks:
      - backend
    
    volumes:
      - ${NC_VOLUME_LOCATION}:/var/www/nextcloud
      - ${NC_DATA_LOCATION}:/var/nextcloud/data

    ports:
      # Web ports
      - "80:80"
      - "443:443"

    depends_on:
      db:
        condition: service_healthy

    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.nextcloud.rule=Host(`cloud.localhost`)"
      # - "traefik.http.routers.nextcloud.entrypoints=websecure"
      # - "traefik.http.routers.nextcloud.tls=true"
      # - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      # - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
      # - "traefik.http.routers.nextcloud.service=nextcloud"


# ---------------------------------------------------------------------------------------------------------------------- #

  db:
    image: mariadb:10.11
    pull_policy: if_not_present
    container_name: mariadb
    restart: always
    
    expose: 
      - 3306
    
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    volumes:
      - ${DB_LOCATION}:/var/lib/mysql:Z
      # Custom config file with recommended setting for nextcloud
      - ./mariadb-cnf.d:/etc/mysql/conf.d:ro

    networks: 
      - backend

networks:
  backend:
    name: backend
